# Generated by Django 3.2.14 on 2022-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='creation_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime image uploaded'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_size',
            field=models.CharField(max_length=20),
        ),
    ]
