# Generated by Django 4.0.5 on 2022-07-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('image_namme',), name='image name unique constraint'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tag_name',), name='tag name unique constraint'),
        ),
    ]
