# Generated by Django 3.2.14 on 2022-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20220716_1012'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagetaglinkage',
            name='image and tag link constraint',
        ),
        migrations.RemoveIndex(
            model_name='imagetaglinkage',
            name='image_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='imagetaglinkage',
            name='tag_id_idx',
        ),
        migrations.RemoveField(
            model_name='imagetaglinkage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='imagetaglinkage',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='imagetaglinkage',
            name='image_name',
            field=models.CharField(default='default_image_name', max_length=200),
        ),
        migrations.AddField(
            model_name='imagetaglinkage',
            name='tag_name',
            field=models.CharField(default='default_tag_name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='imagetaglinkage',
            index=models.Index(fields=['image_name'], name='image_name_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetaglinkage',
            index=models.Index(fields=['tag_name'], name='tag_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagetaglinkage',
            constraint=models.UniqueConstraint(fields=('image_name', 'tag_name'), name='image and tag name link constraint'),
        ),
    ]
