# Generated by Django 4.0.5 on 2022-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_auto_20220716_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_hash",
            field=models.CharField(default="", max_length=64),
        ),
    ]
