# Generated by Django 3.2.14 on 2022-08-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20220803_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetaglinkage',
            name='image_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagetaglinkage',
            name='tag_name',
            field=models.CharField(max_length=200),
        ),
    ]
