# Generated by Django 4.0.5 on 2022-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_image_hash_image_image unique constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_thumbnail',
            field=models.CharField(max_length=5000),
        ),
    ]
