# Generated by Django 3.2.14 on 2022-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20220805_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
