# Generated by Django 3.2.14 on 2022-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_image_image_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('message_type', models.CharField(max_length=50)),
                ('response_rate', models.CharField(max_length=200)),
                ('campaign_thumbnail_url', models.CharField(max_length=50)),
                ('creation_datetime', models.DateTimeField(auto_now=True, verbose_name='datetime image uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImageLinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=50)),
                ('creation_datetime', models.DateTimeField(verbose_name='datetime linkage created')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTagLinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=200)),
                ('tag_name', models.CharField(max_length=200)),
                ('creation_datetime', models.DateTimeField(verbose_name='datetime linkage created')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageTagLinkage',
        ),
        migrations.AddIndex(
            model_name='campaigntaglinkage',
            index=models.Index(fields=['campaign_id'], name='campaign_id_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntaglinkage',
            index=models.Index(fields=['tag_name'], name='tag_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigntaglinkage',
            constraint=models.UniqueConstraint(fields=('campaign_id', 'tag_name'), name='campaign and tag name link constraint'),
        ),
        migrations.AddIndex(
            model_name='campaignimagelinkage',
            index=models.Index(fields=['campaign_id'], name='campaign_id_image_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignimagelinkage',
            index=models.Index(fields=['image_name'], name='image_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignimagelinkage',
            constraint=models.UniqueConstraint(fields=('campaign_id', 'image_name'), name='campaign and image name link constraint'),
        ),
    ]
