# Generated by Django 3.2.14 on 2022-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20220817_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hsbc_vs_non_hsbc',
            field=models.CharField(default='HSBC', max_length=10),
            preserve_default=False,
        ),
    ]
