# Generated by Django 3.2.14 on 2022-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_campaign_hsbc_vs_non_hsbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_thumbnail_url',
            field=models.CharField(max_length=200),
        ),
    ]
