# Generated by Django 3.2.14 on 2022-08-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_alter_campaign_campaign_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_desc',
        ),
    ]
