# Generated by Django 3.2.14 on 2022-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_remove_image_image_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignImageLinkage',
        ),
        migrations.AddField(
            model_name='image',
            name='campaign_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
