# Generated by Django 3.2.14 on 2022-08-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_image_image_hash_image_image unique constraint'),
        ('image', '0010_auto_20220817_0839'),
    ]

    operations = [
    ]
