# Generated by Django 3.2.14 on 2022-08-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_image_image_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_desc',
        ),
    ]
