# Generated by Django 3.2.14 on 2022-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_remove_image_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_thumbnail',
            field=models.BinaryField(),
        ),
    ]
