# Generated by Django 3.2.14 on 2022-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_alter_image_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumbnail',
        ),
        migrations.AddField(
            model_name='image',
            name='image_thumbnail_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
