# Generated by Django 4.0.5 on 2022-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0016_auto_20220819_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='create_by',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creation_datetime',
            field=models.DateTimeField(verbose_name='datetime campaign created'),
        ),
    ]
